server:
  port: 8761
  # 关闭保护机制，默认true
  enable-self-preservation: false
  # 剔除失效服务间隔，默认60000
  eviction-interval-timer-in-ms: 3000

spring:
  security:
    user:
      name: user                # 配置登录的账号是user
      password: 123     # 配置登录的密码是password123

eureka:
  client:
     # 是否要注册到其他Eureka Server实例
      register-with-eureka: false
      # 是否要从其他Eureka Server实例获取数据
      fetch-registry: false
      serviceUrl:
        defaultZone: http://user:123@localhost:8761/eureka
   #自我保护模式
  server:
    enable-self-preservation: true
    #踢掉服务间隔
    eviction-interval-timer-in-ms: 10000
    #阈值更新的时间间隔，单位为毫秒，默认为15 * 60 * 1000
    renewal-threshold-update-interval-ms: 900000
    #阈值因子，默认是0.85，如果阈值比最小值大，则自我保护模式开启
    renewal-percent-threshold: 0.85
    #清理任务程序被唤醒的时间间隔，清理过期的增量信息，单位为毫秒，默认为30 * 1000
    delta-retention-timer-interval-in-ms: 20000
