server:
  port: 8761
  # 关闭保护机制，默认true
  enable-self-preservation: false
  # 剔除失效服务间隔，默认60000
  eviction-interval-timer-in-ms: 3000

spring:
  security:
    user:
      name: user                # 配置登录的账号是user
      password: 123     # 配置登录的密码是password123

eureka:
  client:
     # 是否要注册到其他Eureka Server实例
      register-with-eureka: false
      # 是否要从其他Eureka Server实例获取数据
      fetch-registry: false
      serviceUrl:
        defaultZone: http://user:123@localhost:8761/eureka


