server:
  port: 8004
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://user:123@localhost:8761/eureka
       #开启健康检查
    healthcheck:
      enabled: true
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 20
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30

spring:
  application:
    # 指定注册到eureka server上的服务名称，对于电影微服务，本系列将名称设为microservice-consumer-movie
    name: micro-consumer-hystrix
management:
  endpoint:
    health:
      show-details: always
logging:
  file: ${spring.application.name}/logs/app.log
  level:
     com.demo: debug
  root: info
