server:
  port: 8001
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
spring:
  application:
    # 指定注册到eureka server上的服务名称，对于电影微服务，本系列将名称设为microservice-consumer-movie
    name: micro-consumer

spring:
  security:
    user:
      name: user                # 配置登录的账号是user
      password: 123     # 配置登录的密码是password123